### ISSUE TITLE
Demo fails to render on Hugo Themes

### ISSUE THREAD

**Issue by onedrawingperday** [d-kusk/minimage#58]
Hello @d-kusk 

Apparently I hadn't checked out your theme's demo with the latest changes and now the demo fails to render:
```
10:31:17 PM:  ==== PROCESSING  minimage  ======
10:31:17 PM: Building site for theme minimage using default content to ../themeSite/static/theme/minimage/
10:31:17 PM: Error: "/opt/build/repo/minimage/exampleSite/config.toml:15:1": unmarshal failed: Near line 15 (last key parsed 'params.mainSections'): strings cannot contain newlines
10:31:17 PM: FAILED to create exampleSite for minimage
```

To fix the above please remove [line 15](https://github.com/d-kusk/minimage/blob/master/exampleSite/config.toml#L15) of `exampleSite/config.toml`

The above ERROR is due to the missing quote in `"tags`

However note that I am requesting that you delete this entire line because Hugo detects `mainSections` internally and there is no need to enter `"post"`

Also note that `mainSections` are not intended for categories or tags. These are taxonomies which are different.

Once you do the above feel free to close this issue.

Thank you

**Comment by dsk52** [comment]
@onedrawingperday Thank you for letting me know.
confirm one more time.

**Comment by loveless-codr** [comment]
Hey! I've been working with this theme for a little bit and I ran into a problem involving mainSections. I've found that Hugo sometimes won't render the appropriate type on the homepage without a predefined mainSections. In my case, I think it was because of some issues with my cache, but for another new user, it would probably be less confusing to just have mainSections defined in the configuration file.

Also, I saw the issue that it raised previously. Maybe just mainSections = [ "post" ] would suffice?

Thanks

**Comment by dsk52** [comment]
@loveless-codr Thanks for your comment. 

It hasn't happened without writing the description at the moment, but what kind of article did you generate?


In the comments above,

> However note that I am requesting that you delete this entire line because Hugo detects mainSections internally and there is no need to enter "post"

https://github.com/d-kusk/minimage/issues/58#issue-484855528
