### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by yingxiayin** [d-kusk/minimage#66]
When I use http: / / localhost: 1313 /, everything is normal, but after I Hugo, as a GitHub page, I can only open the homepage

**Comment by dsk52** [comment]
@yingxiayin 
Hi. Thanks for using.
Is this repository generated page using my theme?
https://github.com/yingxiayin/yingxiayin.github.io

In Hugo, you should be able to set the URL of the site with baseurl in config.toml, what is this?
That's because when I generate HTML, I use CSS path and so on, so I think I couldn't set it like './'.

**Comment by yingxiayin** [comment]
oh yes 
but when i set the URL` baseurl = "http://sethisbomb.com" `, the home page `index.html` would lost css

**Comment by yingxiayin** [comment]
<img width="1002" alt="截屏2020-02-2113 36 00" src="https://user-images.githubusercontent.com/34766702/75007158-34332b00-54af-11ea-8f6c-90bf2d7b6d36.png">

**Comment by yingxiayin** [comment]
I changed the baseURL to https://yingxiayin.github.io/ , CSS seems to be working.
Thanks for your help, the theme is useful and beautiful!!
